/** @type {import('next-sitemap').IConfig} */
module.exports = {
  siteUrl: 'https://youtil.kr',
  generateRobotsTxt: true,
  changefreq: 'weekly',
  priority: 0.7,
  sitemapSize: 5000,
  additionalPaths: async (config) => [
    await config.transform(config, '/'),
    await config.transform(config, '/about'),
    await config.transform(config, '/contact'),
    await config.transform(config, '/privacy'),
    await config.transform(config, '/terms'),
    await config.transform(config, '/tools'),
    // 금융
    await config.transform(config, '/tools/finance'),
    await config.transform(config, '/tools/finance/salary'),
    await config.transform(config, '/tools/finance/loan'),
    await config.transform(config, '/tools/finance/compound'),
    await config.transform(config, '/tools/finance/stock'),
    await config.transform(config, '/tools/finance/vat'),
    await config.transform(config, '/tools/finance/dividend'),
    await config.transform(config, '/tools/finance/inheritance'),
    await config.transform(config, '/tools/finance/car-cost'),
    await config.transform(config, '/tools/finance/real-estate'),
    await config.transform(config, '/tools/finance/cost-rate'),
    await config.transform(config, '/tools/finance/installment'),
    await config.transform(config, '/tools/finance/4-insurance'),
    // 건강·안전
    await config.transform(config, '/tools/health'),
    await config.transform(config, '/tools/health/bmi'),
    await config.transform(config, '/tools/health/bmr'),
    await config.transform(config, '/tools/sports/pace'),
    await config.transform(config, '/tools/health/weightloss'),
    await config.transform(config, '/tools/health/pregnancy'),
    await config.transform(config, '/tools/health/pet'),
    await config.transform(config, '/tools/health/blood-alcohol'),
    await config.transform(config, '/tools/sports/race-predictor'),
    await config.transform(config, '/tools/health/supplement'),
    await config.transform(config, '/tools/health/uv-protection'),
    await config.transform(config, '/tools/sports/one-rm'),
    // 요리·식품
    await config.transform(config, '/tools/cooking'),
    await config.transform(config, '/tools/cooking/recipe'),
    await config.transform(config, '/tools/cooking/thawing'),
    await config.transform(config, '/tools/cooking/unit'),
    await config.transform(config, '/tools/cooking/sourdough'),
    await config.transform(config, '/tools/cooking/frying'),
    await config.transform(config, '/tools/cooking/nuts'),
    await config.transform(config, '/tools/cooking/serving'),
    await config.transform(config, '/tools/cooking/food-storage'),
    await config.transform(config, '/tools/cooking/substitute'),
    await config.transform(config, '/tools/cooking/baker-percent'),
    // 생활
    await config.transform(config, '/tools/life'),
    await config.transform(config, '/tools/life/lotto'),
    await config.transform(config, '/tools/life/random'),
    await config.transform(config, '/tools/life/ladder'),
    await config.transform(config, '/tools/life/dutch'),
    await config.transform(config, '/tools/life/zodiac'),
    await config.transform(config, '/tools/life/pomodoro'),
    await config.transform(config, '/tools/life/alcohol'),
    await config.transform(config, '/tools/life/golden-ratio'),
    await config.transform(config, '/tools/life/golf-handicap'),
    await config.transform(config, '/tools/life/drake'),
    await config.transform(config, '/tools/life/laundry-dry'),
    await config.transform(config, '/tools/life/monty-hall'),
    await config.transform(config, '/tools/life/fart-risk'),
    await config.transform(config, '/tools/life/unit-price'),
    await config.transform(config, '/tools/life/golf-cost'),
    await config.transform(config, '/tools/life/golf-distance'),
    // 인테리어
    await config.transform(config, '/tools/interior'),
    await config.transform(config, '/tools/interior/wallpaper'),
    await config.transform(config, '/tools/interior/paint'),
    await config.transform(config, '/tools/interior/room-area'),
    await config.transform(config, '/tools/interior/curtain-blind'),
    await config.transform(config, '/tools/interior/lighting'),
    await config.transform(config, '/tools/interior/ac-capacity'),
    await config.transform(config, '/tools/interior/flooring'),
    await config.transform(config, '/tools/interior/molding'),
    // 스포츠
    await config.transform(config, '/tools/sports'),
    await config.transform(config, '/tools/sports/football-points'),
    await config.transform(config, '/tools/sports/baseball-stats'),
    await config.transform(config, '/tools/sports/fight-weight'),
    await config.transform(config, '/tools/sports/interval-training'),
    // 단위
    await config.transform(config, '/tools/unit'),
    await config.transform(config, '/tools/unit/area'),
    await config.transform(config, '/tools/unit/length'),
    await config.transform(config, '/tools/unit/weight'),
    await config.transform(config, '/tools/unit/size'),
    await config.transform(config, '/tools/unit/temperature'),
    await config.transform(config, '/tools/unit/time'),
    await config.transform(config, '/tools/unit/battery'),
    await config.transform(config, '/tools/unit/fuel-economy'),
    await config.transform(config, '/tools/unit/tire-pressure'),
    // 날짜
    await config.transform(config, '/tools/date'),
    await config.transform(config, '/tools/date/age'),
    await config.transform(config, '/tools/date/dday'),
    await config.transform(config, '/tools/date/military'),
    await config.transform(config, '/tools/date/history-era'),
    await config.transform(config, '/tools/date/lunar'),
    await config.transform(config, '/tools/date/jet-lag'),
    await config.transform(config, '/tools/date/life-time'),
    // 음악
    await config.transform(config, '/tools/music'),
    await config.transform(config, '/tools/music/bpm'),
    await config.transform(config, '/tools/music/frequency'),
    await config.transform(config, '/tools/music/capo'),
    await config.transform(config, '/tools/music/tap-tempo'),
    await config.transform(config, '/tools/music/chord'),
    // 교육·학습
    await config.transform(config, '/tools/edu'),
    await config.transform(config, '/tools/edu/planet-comparison'),
    await config.transform(config, '/tools/edu/cosmic-calendar'),
    await config.transform(config, '/tools/edu/circuit-simulator'),
    await config.transform(config, '/tools/edu/sound-speed'),
    await config.transform(config, '/tools/edu/review-interval'),
    await config.transform(config, '/tools/edu/cognitive-test'),
    await config.transform(config, '/tools/edu/fermi-estimate'),
    // 개발자
    await config.transform(config, '/tools/dev'),
    await config.transform(config, '/tools/dev/charcount'),
    await config.transform(config, '/tools/dev/base64'),
    await config.transform(config, '/tools/dev/json'),
    await config.transform(config, '/tools/dev/lorem'),
    await config.transform(config, '/tools/dev/color'),
    await config.transform(config, '/tools/dev/css-converter'),
    await config.transform(config, '/tools/dev/number-base'),
  ],
  transform: async (config, path) => {
    const highPriority = [
      '/',
      '/tools/finance/salary',
      '/tools/date/age',
      '/tools/life/lotto',
      '/tools/health/bmi',
      '/tools/finance/stock',
      '/tools/date/military',
      '/tools/life/dutch',
    ]
    return {
      loc: path,
      changefreq: config.changefreq,
      priority: highPriority.includes(path) ? 1.0 : 0.7,
      lastmod: new Date().toISOString(),
    }
  },
}
