/* ──────────────────────────────────────────────────────
   tech-stack/stackData.ts
   2026년 5월 기준 인기 풀스택 데이터 — 7 카테고리 × 6+ 스택
   ────────────────────────────────────────────────────── */

export type Category = 'frontend' | 'backend' | 'db' | 'auth' | 'hosting' | 'payment' | 'analytics' | 'mobile'

export interface StackScores {
  speed:       number  // 개발 속도 1~10
  scale:       number  // 확장성
  cost:        number  // 비용 효율 (높을수록 저렴)
  learning:    number  // 학습 곡선 (높을수록 쉬움)
  ecosystem:   number  // 생태계 크기
  performance: number  // 성능
  koreaJobs:   number  // 한국 채용 수요
}

export interface Stack {
  id: string
  category: Category
  label: string
  emoji: string
  desc:  string
  scores: StackScores
  setupCmd?: string         // 설치 명령어
  monthlyCostUsd: [number, number]  // [low, high] — 1만 사용자 기준
  learningWeeks: [number, number]   // [초보, 중급]
  pros: string[]
  cons: string[]
  /** 적합 프로젝트 유형 — 점수 가중치 */
  bestFor:  string[]
  /** 부적합 — 안티패턴 */
  worstFor: string[]
  /** 한국 채용·생태 메모 */
  koreaNote?: string
  url?: string
}

/* ───── Frontend ───── */
export const FRONTENDS: Stack[] = [
  {
    id: 'next', category: 'frontend',
    label: 'Next.js 16', emoji: '▲',
    desc: '풀스택 React 프레임워크 (App Router·Server Components·Turbopack)',
    scores: { speed: 9, scale: 10, cost: 7, learning: 7, ecosystem: 10, performance: 9, koreaJobs: 10 },
    setupCmd: 'npx create-next-app@latest my-app --typescript --tailwind --app',
    monthlyCostUsd: [0, 20],
    learningWeeks: [3, 1],
    pros: ['SSR/SSG/ISR 모두 지원', 'Vercel 0-config 배포', 'React 생태계 직결', '한국 채용 1순위'],
    cons: ['App Router 학습 곡선 있음', 'Server Component 멘탈 모델 필요'],
    bestFor: ['웹앱', 'SSR', 'MVP', 'SEO 중요', '한국형 SaaS'],
    worstFor: ['단순 정적 블로그 (Astro 권장)', '오프라인 우선 앱'],
    koreaNote: '토스·당근·쿠팡·네이버 모두 Next.js 활용 — 채용 시장 압도적',
    url: 'https://nextjs.org',
  },
  {
    id: 'remix', category: 'frontend',
    label: 'Remix (React Router 7)', emoji: '💿',
    desc: 'React Router 7로 통합. 웹 표준 중심 풀스택',
    scores: { speed: 8, scale: 9, cost: 7, learning: 7, ecosystem: 7, performance: 9, koreaJobs: 4 },
    setupCmd: 'npx create-react-router@latest my-app',
    monthlyCostUsd: [0, 20],
    learningWeeks: [3, 1],
    pros: ['Web Standard (Form·Loader)', '서버 자유 (Vercel/CF/AWS)', '진보적 향상'],
    cons: ['생태계 Next 대비 작음', '한국 채용 미미'],
    bestFor: ['웹앱', 'Form 중심', 'SEO 중요'],
    worstFor: ['정적 사이트', '한국 채용 우선'],
    koreaNote: '한국 채용은 매우 적음 (대규모 사용 사례 X)',
    url: 'https://remix.run',
  },
  {
    id: 'astro', category: 'frontend',
    label: 'Astro 5', emoji: '🚀',
    desc: '콘텐츠 우선 사이트. 0kb JS by default',
    scores: { speed: 10, scale: 8, cost: 9, learning: 9, ecosystem: 8, performance: 10, koreaJobs: 3 },
    setupCmd: 'npm create astro@latest',
    monthlyCostUsd: [0, 5],
    learningWeeks: [1, 0.5],
    pros: ['최고 성능', 'React/Vue/Svelte 혼용', 'SEO 최적', 'Markdown 친화'],
    cons: ['동적 인터랙션 약함', '복잡 SaaS 부적합'],
    bestFor: ['블로그', '마케팅 정적 사이트', '문서 사이트', 'SEO 매우중요'],
    worstFor: ['실시간 협업', '대시보드', 'SPA'],
    url: 'https://astro.build',
  },
  {
    id: 'sveltekit', category: 'frontend',
    label: 'SvelteKit', emoji: '🔥',
    desc: 'Svelte 5 기반 풀스택. 컴파일 시점 최적화',
    scores: { speed: 9, scale: 8, cost: 8, learning: 8, ecosystem: 6, performance: 10, koreaJobs: 2 },
    setupCmd: 'npx sv create my-app',
    monthlyCostUsd: [0, 20],
    learningWeeks: [2, 1],
    pros: ['번들 작음·빠름', '문법 간결', 'Runes (반응성 명시)'],
    cons: ['React 대비 라이브러리 적음', '한국 채용 거의 없음'],
    bestFor: ['성능 중시', '소규모 팀', '개인 프로젝트'],
    worstFor: ['한국 취업 목적', '엔터프라이즈'],
    url: 'https://kit.svelte.dev',
  },
  {
    id: 'nuxt', category: 'frontend',
    label: 'Nuxt 3', emoji: '💚',
    desc: 'Vue 3 풀스택 프레임워크. Nitro 서버 엔진',
    scores: { speed: 9, scale: 9, cost: 8, learning: 8, ecosystem: 8, performance: 9, koreaJobs: 5 },
    setupCmd: 'npx nuxi@latest init my-app',
    monthlyCostUsd: [0, 20],
    learningWeeks: [2, 1],
    pros: ['Vue 친화·간결', 'Nitro 다중 배포', 'Composition API'],
    cons: ['React 채용보다 적음'],
    bestFor: ['Vue 경험자', '빠른 개발'],
    worstFor: ['React 환경 통합'],
    koreaNote: 'Vue.js 사용 회사 (라인·NHN·토스 일부) 채용',
    url: 'https://nuxt.com',
  },
  {
    id: 'vite', category: 'frontend',
    label: 'Vite + React (SPA)', emoji: '⚡',
    desc: 'Vite 5 + React 19. SSR 없는 순수 SPA',
    scores: { speed: 10, scale: 7, cost: 9, learning: 8, ecosystem: 10, performance: 8, koreaJobs: 9 },
    setupCmd: 'npm create vite@latest my-app -- --template react-ts',
    monthlyCostUsd: [0, 5],
    learningWeeks: [2, 0.5],
    pros: ['HMR 가장 빠름', '단순한 클라이언트 앱에 최적', 'CDN 호스팅 무료'],
    cons: ['SEO 약함', '서버 로직은 별도'],
    bestFor: ['사내 어드민', '대시보드', 'SPA'],
    worstFor: ['SEO 매우중요', '마케팅 사이트'],
    koreaNote: 'CRA 후속으로 가장 인기. 사내 도구·대시보드 표준',
    url: 'https://vitejs.dev',
  },
]

/* ───── Backend ───── */
export const BACKENDS: Stack[] = [
  {
    id: 'next-api', category: 'backend',
    label: 'Next.js Route Handlers', emoji: '▲',
    desc: 'Next.js 내장 API. Server Actions로 풀스택 통합',
    scores: { speed: 10, scale: 9, cost: 8, learning: 8, ecosystem: 10, performance: 8, koreaJobs: 9 },
    setupCmd: '# Next.js와 함께',
    monthlyCostUsd: [0, 20],
    learningWeeks: [1, 0.5],
    pros: ['Frontend와 동일 코드베이스', 'TypeScript end-to-end', 'Vercel 자동 스케일'],
    cons: ['장시간 작업 부적합 (10s 제한)', '대용량 처리 별도'],
    bestFor: ['MVP', 'CRUD', 'BFF (Backend for Frontend)'],
    worstFor: ['ML 추론', '비디오 인코딩'],
  },
  {
    id: 'hono', category: 'backend',
    label: 'Hono', emoji: '🔥',
    desc: 'Edge·Bun·Node 모두 지원. 초경량·고성능',
    scores: { speed: 9, scale: 9, cost: 10, learning: 9, ecosystem: 7, performance: 10, koreaJobs: 4 },
    setupCmd: 'npm create hono@latest my-api',
    monthlyCostUsd: [0, 5],
    learningWeeks: [1, 0.5],
    pros: ['Cloudflare Workers 친화', '빠른 cold start', 'Express 유사 API'],
    cons: ['생태계 신규', '레거시 통합 시 주의'],
    bestFor: ['API 서버', 'Edge 함수', '저비용 백엔드'],
    worstFor: ['엔터프라이즈 레거시'],
  },
  {
    id: 'fastapi', category: 'backend',
    label: 'FastAPI', emoji: '🐍',
    desc: 'Python 비동기 API. Pydantic·OpenAPI 자동',
    scores: { speed: 9, scale: 8, cost: 8, learning: 8, ecosystem: 9, performance: 8, koreaJobs: 6 },
    setupCmd: 'pip install fastapi[all]',
    monthlyCostUsd: [5, 50],
    learningWeeks: [2, 1],
    pros: ['Type hint 기반 자동 문서', '비동기 (async/await)', 'AI/ML 통합 쉬움'],
    cons: ['배포 복잡 (Vercel 미지원)', 'Node 대비 차가운 시작'],
    bestFor: ['AI 챗봇·LLM 앱', '데이터 분석', 'ML 추론 API'],
    worstFor: ['풀스택 통합 (Next.js 권장)'],
    koreaNote: 'AI 스타트업·데이터 회사에서 표준',
  },
  {
    id: 'express', category: 'backend',
    label: 'Express.js', emoji: '🟢',
    desc: '가장 보편적인 Node.js 프레임워크',
    scores: { speed: 7, scale: 8, cost: 8, learning: 9, ecosystem: 10, performance: 7, koreaJobs: 9 },
    setupCmd: 'npm i express',
    monthlyCostUsd: [5, 30],
    learningWeeks: [1, 0.5],
    pros: ['생태계 압도적', '레거시 호환', '한국 채용 풍부'],
    cons: ['모던 기능 부족 (TS·async 부수적)', 'Hono 대비 느림'],
    bestFor: ['레거시 통합', 'Node 익숙한 팀'],
    worstFor: ['신규 프로젝트 (Hono/NestJS 권장)'],
    koreaNote: '레거시 시스템·중대형 SI에서 표준',
  },
  {
    id: 'nestjs', category: 'backend',
    label: 'NestJS', emoji: '🐱',
    desc: 'Angular 풍 의존성 주입. 엔터프라이즈 Node',
    scores: { speed: 6, scale: 10, cost: 7, learning: 5, ecosystem: 9, performance: 7, koreaJobs: 8 },
    setupCmd: 'npm i -g @nestjs/cli && nest new my-api',
    monthlyCostUsd: [5, 50],
    learningWeeks: [4, 2],
    pros: ['DI·모듈 구조', '대규모 협업 용이', 'TypeORM·GraphQL 통합'],
    cons: ['보일러플레이트 많음', '소규모에 부적합'],
    bestFor: ['중대규모 팀', '엔터프라이즈 API'],
    worstFor: ['MVP', '1인 프로젝트'],
    koreaNote: '카카오·우아한형제·라인 등 대규모에서 인기',
  },
  {
    id: 'spring', category: 'backend',
    label: 'Spring Boot', emoji: '☕',
    desc: 'Java 표준. 엔터프라이즈 안정성',
    scores: { speed: 5, scale: 10, cost: 6, learning: 4, ecosystem: 10, performance: 9, koreaJobs: 10 },
    setupCmd: '# start.spring.io 또는 IntelliJ',
    monthlyCostUsd: [10, 100],
    learningWeeks: [6, 3],
    pros: ['엔터프라이즈 표준', '대량 트래픽 검증', '한국 채용 1순위 (대기업)'],
    cons: ['보일러플레이트', 'JVM 메모리 사용'],
    bestFor: ['대기업 SI', '대규모 서비스', '레거시 통합'],
    worstFor: ['MVP', '서버리스'],
    koreaNote: '삼성·LG·금융권·SI 모두 Java/Spring 우세 — 채용 시장 1위',
  },
  {
    id: 'django', category: 'backend',
    label: 'Django', emoji: '🦄',
    desc: 'Python 풀스택. Admin 자동 생성',
    scores: { speed: 9, scale: 8, cost: 7, learning: 7, ecosystem: 9, performance: 7, koreaJobs: 5 },
    setupCmd: 'pip install django && django-admin startproject mysite',
    monthlyCostUsd: [5, 50],
    learningWeeks: [3, 1],
    pros: ['Admin 페이지 자동', 'ORM 강력', '풀스택 통합'],
    cons: ['Async 약함', 'API 설계 시 DRF 추가 필요'],
    bestFor: ['사내 어드민', '컨텐츠 관리'],
    worstFor: ['실시간', 'Edge'],
  },
]

/* ───── Database ───── */
export const DATABASES: Stack[] = [
  {
    id: 'supabase-pg', category: 'db',
    label: 'Supabase Postgres', emoji: '🐘',
    desc: 'Postgres + Realtime + Storage 올인원',
    scores: { speed: 10, scale: 9, cost: 9, learning: 9, ecosystem: 9, performance: 9, koreaJobs: 7 },
    setupCmd: 'npx supabase init',
    monthlyCostUsd: [0, 25],
    learningWeeks: [1, 0.5],
    pros: ['무료 티어 넉넉', 'Realtime 내장', 'Auth·Storage 통합'],
    cons: ['vendor lock-in (Postgres 자체는 이전 가능)'],
    bestFor: ['MVP', 'SaaS', '실시간 협업'],
    worstFor: ['초대형 트래픽 (자체 운영 권장)'],
    url: 'https://supabase.com',
  },
  {
    id: 'neon', category: 'db',
    label: 'Neon (Serverless Postgres)', emoji: '⚡',
    desc: 'Serverless Postgres. Branch·Auto-pause',
    scores: { speed: 10, scale: 10, cost: 10, learning: 9, ecosystem: 8, performance: 9, koreaJobs: 5 },
    setupCmd: '# neon.tech 가입 → 연결 문자열',
    monthlyCostUsd: [0, 19],
    learningWeeks: [1, 0.5],
    pros: ['DB 분기·복제', 'Auto-pause 비용 절약', 'Edge 친화'],
    cons: ['Cold start 가능'],
    bestFor: ['Vercel/Cloudflare 배포', '저비용'],
    worstFor: ['지속 고부하'],
    url: 'https://neon.tech',
  },
  {
    id: 'postgres-self', category: 'db',
    label: 'Self-hosted Postgres', emoji: '🐘',
    desc: '직접 운영 (AWS RDS / NCloud / 자체)',
    scores: { speed: 6, scale: 10, cost: 6, learning: 6, ecosystem: 10, performance: 10, koreaJobs: 9 },
    setupCmd: '# Docker / RDS / NCloud 설치',
    monthlyCostUsd: [20, 200],
    learningWeeks: [3, 1],
    pros: ['완전 통제', '대규모 검증', '데이터 주권'],
    cons: ['운영 부담', '백업·HA 직접'],
    bestFor: ['엔터프라이즈', '데이터 민감'],
    worstFor: ['MVP', '1인 프로젝트'],
    koreaNote: '금융·공공기관 표준 (개인정보보호법 대응)',
  },
  {
    id: 'mongodb', category: 'db',
    label: 'MongoDB Atlas', emoji: '🍃',
    desc: 'NoSQL Document DB. Atlas Serverless',
    scores: { speed: 9, scale: 9, cost: 8, learning: 8, ecosystem: 9, performance: 8, koreaJobs: 7 },
    setupCmd: '# atlas.mongodb.com 가입',
    monthlyCostUsd: [0, 60],
    learningWeeks: [2, 1],
    pros: ['스키마 유연', 'Aggregation 강력'],
    cons: ['관계형 쿼리 약함', '트랜잭션 제약'],
    bestFor: ['IoT 데이터', '로그·이벤트', 'CMS'],
    worstFor: ['금융 트랜잭션', '복잡 조인'],
  },
  {
    id: 'sqlite', category: 'db',
    label: 'SQLite (Turso/D1)', emoji: '📦',
    desc: 'Edge SQLite (Turso/Cloudflare D1). 무료',
    scores: { speed: 10, scale: 7, cost: 10, learning: 9, ecosystem: 7, performance: 9, koreaJobs: 3 },
    setupCmd: 'npm i @libsql/client',
    monthlyCostUsd: [0, 5],
    learningWeeks: [1, 0.5],
    pros: ['거의 무료', 'Edge replication', '단순'],
    cons: ['쓰기 제약', '대규모 부적합'],
    bestFor: ['저비용 MVP', '읽기 위주', '블로그'],
    worstFor: ['대규모 쓰기', '실시간 협업'],
  },
  {
    id: 'redis', category: 'db',
    label: 'Redis (Upstash)', emoji: '🔴',
    desc: '캐시·큐 (보조 DB). Upstash Serverless',
    scores: { speed: 10, scale: 10, cost: 9, learning: 8, ecosystem: 10, performance: 10, koreaJobs: 8 },
    setupCmd: '# upstash.com 가입',
    monthlyCostUsd: [0, 20],
    learningWeeks: [1, 0.5],
    pros: ['초고속', 'Rate limit·Session', 'Pub/Sub'],
    cons: ['주 DB 아님', '비용 누적 시 비쌈'],
    bestFor: ['캐시', '실시간 카운터', 'Rate limit'],
    worstFor: ['주 데이터 저장'],
  },
]

/* ───── Auth ───── */
export const AUTHS: Stack[] = [
  {
    id: 'clerk', category: 'auth',
    label: 'Clerk', emoji: '🔐',
    desc: '풀 인증 SaaS. UI 컴포넌트 즉시 사용',
    scores: { speed: 10, scale: 9, cost: 5, learning: 10, ecosystem: 8, performance: 9, koreaJobs: 5 },
    setupCmd: 'npm i @clerk/nextjs',
    monthlyCostUsd: [0, 25],
    learningWeeks: [0.5, 0.2],
    pros: ['1분 설정', 'OAuth·MFA 즉시', 'Pre-built UI'],
    cons: ['10k+ MAU 시 유료', '한국 OAuth 추가 작업'],
    bestFor: ['MVP', '빠른 출시'],
    worstFor: ['저예산 1만+ 사용자', '한국 OAuth 우선'],
    url: 'https://clerk.com',
  },
  {
    id: 'supabase-auth', category: 'auth',
    label: 'Supabase Auth', emoji: '🟢',
    desc: 'DB·Auth·Storage 통합. RLS 강력',
    scores: { speed: 9, scale: 9, cost: 10, learning: 8, ecosystem: 9, performance: 9, koreaJobs: 6 },
    setupCmd: 'npm i @supabase/supabase-js',
    monthlyCostUsd: [0, 25],
    learningWeeks: [1, 0.5],
    pros: ['무료 50k MAU', 'RLS로 권한 관리', 'OAuth 다수'],
    cons: ['UI 직접 구현', '카카오 별도'],
    bestFor: ['Supabase 사용 시', '저예산'],
    worstFor: ['Pre-built UI 필요'],
  },
  {
    id: 'auth-js', category: 'auth',
    label: 'Auth.js (NextAuth v5)', emoji: '🔑',
    desc: 'Next.js 친화. OAuth provider 다수',
    scores: { speed: 8, scale: 9, cost: 10, learning: 7, ecosystem: 10, performance: 9, koreaJobs: 8 },
    setupCmd: 'npm i next-auth@beta',
    monthlyCostUsd: [0, 0],
    learningWeeks: [1.5, 0.5],
    pros: ['완전 무료', 'OAuth 60+ provider', '카카오·네이버 공식 지원'],
    cons: ['DB 직접 구성', 'Pre-built UI 없음'],
    bestFor: ['Next.js + 한국 OAuth', '저예산'],
    worstFor: ['빠른 MVP'],
    koreaNote: '카카오·네이버 OAuth 공식 provider — 한국 SaaS에 가장 적합',
  },
  {
    id: 'lucia', category: 'auth',
    label: 'Lucia', emoji: '🌟',
    desc: '경량 라이브러리. DB 자체 운영',
    scores: { speed: 7, scale: 9, cost: 10, learning: 6, ecosystem: 6, performance: 10, koreaJobs: 3 },
    monthlyCostUsd: [0, 0],
    learningWeeks: [2, 1],
    pros: ['프레임워크 무관', '코드 통제 100%'],
    cons: ['v3에서 deprecated 안내 — 자체 구현 권장'],
    bestFor: ['커스텀 인증 학습'],
    worstFor: ['프로덕션 신규'],
  },
  {
    id: 'firebase-auth', category: 'auth',
    label: 'Firebase Auth', emoji: '🔥',
    desc: 'Google 구축 인증. iOS/Android 친화',
    scores: { speed: 9, scale: 10, cost: 8, learning: 8, ecosystem: 10, performance: 9, koreaJobs: 7 },
    setupCmd: 'npm i firebase',
    monthlyCostUsd: [0, 25],
    learningWeeks: [1, 0.5],
    pros: ['모바일 친화', 'Google·Apple OAuth', 'Phone Auth'],
    cons: ['Google 락인', '한국 OAuth 별도'],
    bestFor: ['React Native', 'Flutter', 'Google 통합'],
    worstFor: ['카카오·네이버 위주'],
  },
  {
    id: 'kakao-direct', category: 'auth',
    label: '카카오·네이버 직접', emoji: '💛',
    desc: '카카오 SDK + 네이버 API 직접 통합',
    scores: { speed: 6, scale: 9, cost: 10, learning: 5, ecosystem: 7, performance: 9, koreaJobs: 9 },
    setupCmd: '# 카카오 디벨로퍼·네이버 디벨로퍼 등록',
    monthlyCostUsd: [0, 0],
    learningWeeks: [2, 0.5],
    pros: ['한국 사용자 친화', '무료', '카톡 알림 통합 가능'],
    cons: ['초기 설정 복잡 (사업자 등록·심사)', '직접 토큰 관리'],
    bestFor: ['한국형 SaaS', 'B2C'],
    worstFor: ['글로벌 우선'],
    koreaNote: '한국 B2C 표준 — 이메일 가입보다 카카오·네이버 비중 70%+',
  },
]

/* ───── Hosting ───── */
export const HOSTINGS: Stack[] = [
  {
    id: 'vercel', category: 'hosting',
    label: 'Vercel', emoji: '▲',
    desc: 'Next.js 만든 곳. Git push → 자동 배포',
    scores: { speed: 10, scale: 9, cost: 6, learning: 10, ecosystem: 10, performance: 9, koreaJobs: 8 },
    setupCmd: 'npx vercel',
    monthlyCostUsd: [0, 20],
    learningWeeks: [0.1, 0.1],
    pros: ['0-config 배포', 'Edge·CDN 글로벌', 'Preview 환경 자동'],
    cons: ['Pro $20/월', '큰 트래픽 시 비용 ↑'],
    bestFor: ['Next.js', 'MVP', '소·중규모'],
    worstFor: ['초저예산', '대규모 백엔드'],
    url: 'https://vercel.com',
  },
  {
    id: 'netlify', category: 'hosting',
    label: 'Netlify', emoji: '🌐',
    desc: 'JAMstack 1세대. Edge Functions',
    scores: { speed: 10, scale: 8, cost: 7, learning: 10, ecosystem: 9, performance: 9, koreaJobs: 5 },
    setupCmd: 'npx netlify-cli deploy',
    monthlyCostUsd: [0, 19],
    learningWeeks: [0.1, 0.1],
    pros: ['정적 사이트 친화', 'Forms·Identity 내장', 'Plugin 풍부'],
    cons: ['Next.js는 Vercel만 못함'],
    bestFor: ['Astro', '정적 사이트', '블로그'],
    worstFor: ['Next.js Server Component'],
  },
  {
    id: 'cloudflare', category: 'hosting',
    label: 'Cloudflare Pages·Workers', emoji: '☁️',
    desc: 'Edge 우선. 무료 티어 매우 넉넉',
    scores: { speed: 9, scale: 10, cost: 10, learning: 7, ecosystem: 8, performance: 10, koreaJobs: 6 },
    setupCmd: 'npm i -g wrangler && wrangler init',
    monthlyCostUsd: [0, 5],
    learningWeeks: [1, 0.5],
    pros: ['거의 무료', 'Edge 가장 빠름', 'D1·R2·KV 통합'],
    cons: ['Workers 제약 (50ms CPU)', '큰 라이브러리 부적합'],
    bestFor: ['저비용', 'Hono', 'Edge API'],
    worstFor: ['Node 풀 호환 필요'],
  },
  {
    id: 'aws', category: 'hosting',
    label: 'AWS (EC2 / Lambda)', emoji: '☁️',
    desc: '무한 확장성. 학습 곡선 가파름',
    scores: { speed: 5, scale: 10, cost: 6, learning: 4, ecosystem: 10, performance: 9, koreaJobs: 10 },
    monthlyCostUsd: [10, 500],
    learningWeeks: [6, 3],
    pros: ['무한 확장', '서비스 200+', '한국 채용 1순위'],
    cons: ['복잡', '비용 예측 어려움'],
    bestFor: ['엔터프라이즈', '대규모', '한국 대기업'],
    worstFor: ['MVP', '1인 프로젝트'],
    koreaNote: '쿠팡·당근·우아한형제 모두 AWS — 채용 시장 표준',
  },
  {
    id: 'flyio', category: 'hosting',
    label: 'Fly.io', emoji: '🪰',
    desc: '글로벌 region 도커 호스팅',
    scores: { speed: 8, scale: 9, cost: 8, learning: 6, ecosystem: 7, performance: 10, koreaJobs: 3 },
    setupCmd: 'curl -L https://fly.io/install.sh | sh && flyctl launch',
    monthlyCostUsd: [0, 30],
    learningWeeks: [2, 1],
    pros: ['Docker 친화', 'Global region', 'WebSocket 친화'],
    cons: ['한국 region 없음 (도쿄)', '학습 필요'],
    bestFor: ['실시간', 'WebSocket', 'Postgres 가까이'],
    worstFor: ['초보'],
  },
  {
    id: 'railway', category: 'hosting',
    label: 'Railway', emoji: '🚂',
    desc: 'Heroku 후속. PR 환경 자동',
    scores: { speed: 9, scale: 8, cost: 7, learning: 9, ecosystem: 7, performance: 8, koreaJobs: 4 },
    monthlyCostUsd: [5, 30],
    learningWeeks: [0.5, 0.2],
    pros: ['1-click 배포', 'DB 자동 프로비저닝', 'PR 환경'],
    cons: ['$5/월 최소', 'Edge 없음'],
    bestFor: ['풀스택 백엔드', 'PR 미리보기'],
    worstFor: ['정적 사이트'],
  },
]

/* ───── Payment (한국) ───── */
export const PAYMENTS: Stack[] = [
  {
    id: 'toss-payments', category: 'payment',
    label: '토스페이먼츠', emoji: '💙',
    desc: '한국 PG 사실상 표준. 개발자 친화',
    scores: { speed: 10, scale: 10, cost: 8, learning: 9, ecosystem: 9, performance: 9, koreaJobs: 9 },
    setupCmd: 'npm i @tosspayments/payment-sdk',
    monthlyCostUsd: [0, 0],  // 거래 수수료
    learningWeeks: [1, 0.5],
    pros: ['문서 우수', 'SDK 잘 짜임', '카드·계좌·간편결제 통합', '수수료 2.7~3.3%'],
    cons: ['사업자등록 + 심사 필요'],
    bestFor: ['한국형 SaaS', 'B2C', 'B2B'],
    worstFor: ['글로벌 결제 (Stripe 권장)'],
    koreaNote: '2026년 한국 신규 SaaS 80% 이상 토스페이먼츠 — 표준',
    url: 'https://docs.tosspayments.com',
  },
  {
    id: 'portone', category: 'payment',
    label: '포트원 (구 아임포트)', emoji: '🎯',
    desc: '여러 PG 통합 라이브러리',
    scores: { speed: 9, scale: 9, cost: 9, learning: 9, ecosystem: 8, performance: 8, koreaJobs: 6 },
    setupCmd: 'npm i @portone/browser-sdk',
    monthlyCostUsd: [0, 0],
    learningWeeks: [1, 0.5],
    pros: ['PG 변경 쉬움', '통합 대시보드', '간편결제 다수'],
    cons: ['중간 레이어 추가', '한 PG 직접보다 약간 느림'],
    bestFor: ['멀티 PG', '에러 케이스 많은 서비스'],
    worstFor: ['단순 토스페이먼츠 충분 시'],
    url: 'https://portone.io',
  },
  {
    id: 'kakaopay', category: 'payment',
    label: '카카오페이', emoji: '💛',
    desc: '카카오톡 사용자 친화. 단독 또는 PG 통합',
    scores: { speed: 8, scale: 10, cost: 8, learning: 8, ecosystem: 7, performance: 9, koreaJobs: 7 },
    monthlyCostUsd: [0, 0],
    learningWeeks: [1.5, 0.5],
    pros: ['카톡 사용자 친화', '간편 결제'],
    cons: ['단일 결제수단', '심사 까다로움'],
    bestFor: ['B2C 모바일', '카톡 채널 연계'],
    worstFor: ['B2B', '카드 우선'],
  },
  {
    id: 'inicis', category: 'payment',
    label: 'KG이니시스', emoji: '🏦',
    desc: '한국 1세대 PG. 레거시 안정성',
    scores: { speed: 6, scale: 10, cost: 7, learning: 5, ecosystem: 7, performance: 8, koreaJobs: 7 },
    monthlyCostUsd: [0, 0],
    learningWeeks: [3, 1],
    pros: ['업력 길고 안정적', '대기업·금융권 표준'],
    cons: ['문서 구식', '개발자 경험 떨어짐'],
    bestFor: ['엔터프라이즈', '레거시 통합'],
    worstFor: ['신규 스타트업 (토스 권장)'],
    koreaNote: '대기업·금융권은 여전히 이니시스 다수 사용',
  },
  {
    id: 'stripe', category: 'payment',
    label: 'Stripe (글로벌)', emoji: '🌍',
    desc: '글로벌 결제. 한국 카드도 가능',
    scores: { speed: 10, scale: 10, cost: 7, learning: 10, ecosystem: 10, performance: 10, koreaJobs: 5 },
    setupCmd: 'npm i stripe',
    monthlyCostUsd: [0, 0],
    learningWeeks: [0.5, 0.2],
    pros: ['세계 표준', '문서 최고', '구독 결제 강력'],
    cons: ['한국 사업자등록·세금 처리 별도', '카카오페이·계좌이체 X'],
    bestFor: ['글로벌 SaaS', '구독 결제'],
    worstFor: ['한국 전용 서비스'],
  },
]

/* ───── Analytics ───── */
export const ANALYTICS: Stack[] = [
  {
    id: 'vercel-analytics', category: 'analytics',
    label: 'Vercel Analytics', emoji: '▲',
    desc: 'Next.js 통합. 쿠키 X, 가벼움',
    scores: { speed: 10, scale: 9, cost: 7, learning: 10, ecosystem: 8, performance: 10, koreaJobs: 6 },
    setupCmd: 'npm i @vercel/analytics',
    monthlyCostUsd: [0, 10],
    learningWeeks: [0.1, 0.1],
    pros: ['1줄 설정', '쿠키 없음 (GDPR)', 'Web Vitals 자동'],
    cons: ['Vercel 외부 X', '깊은 분석 부족'],
    bestFor: ['Next.js + Vercel', 'Privacy 우선'],
    worstFor: ['상세 분석 필요'],
  },
  {
    id: 'ga4', category: 'analytics',
    label: 'Google Analytics 4', emoji: '📊',
    desc: '무료 표준. 가장 풍부한 기능',
    scores: { speed: 8, scale: 10, cost: 10, learning: 6, ecosystem: 10, performance: 7, koreaJobs: 9 },
    monthlyCostUsd: [0, 0],
    learningWeeks: [2, 1],
    pros: ['무료', '가장 많은 도구', '광고 통합'],
    cons: ['UI 복잡', 'GDPR·동의 필요', '쿠키 사용'],
    bestFor: ['트래픽 분석', '광고 ROI'],
    worstFor: ['Privacy 우선', '단순 도구'],
  },
  {
    id: 'plausible', category: 'analytics',
    label: 'Plausible', emoji: '🔒',
    desc: 'Privacy-first. 쿠키 없음',
    scores: { speed: 10, scale: 8, cost: 7, learning: 10, ecosystem: 7, performance: 10, koreaJobs: 4 },
    setupCmd: '# script tag',
    monthlyCostUsd: [9, 19],
    learningWeeks: [0.1, 0.1],
    pros: ['쿠키 없음 (GDPR·KISA 안전)', '단순 UI', '오픈소스'],
    cons: ['유료 ($9/월~)', 'GA만큼 깊지 않음'],
    bestFor: ['Privacy 우선', '단순 통계'],
    worstFor: ['상세 funnel 분석'],
  },
  {
    id: 'posthog', category: 'analytics',
    label: 'PostHog', emoji: '🦔',
    desc: 'Product Analytics + Session Replay',
    scores: { speed: 8, scale: 9, cost: 8, learning: 7, ecosystem: 8, performance: 8, koreaJobs: 5 },
    setupCmd: 'npm i posthog-js',
    monthlyCostUsd: [0, 50],
    learningWeeks: [1, 0.5],
    pros: ['세션 리플레이', 'Feature Flag 통합', '오픈소스 자체 호스팅 가능'],
    cons: ['Heavy script', 'GDPR 주의'],
    bestFor: ['Product analytics', 'A/B 테스트'],
    worstFor: ['단순 PV 카운트'],
  },
]

/* ───── Mobile ───── */
export const MOBILES: Stack[] = [
  {
    id: 'rn-expo', category: 'mobile',
    label: 'React Native + Expo', emoji: '📱',
    desc: 'JavaScript로 iOS/Android. Expo Router',
    scores: { speed: 9, scale: 9, cost: 9, learning: 9, ecosystem: 9, performance: 8, koreaJobs: 8 },
    setupCmd: 'npx create-expo-app@latest',
    monthlyCostUsd: [0, 30],
    learningWeeks: [3, 1],
    pros: ['React 친화', 'Hot Reload', 'EAS Build'],
    cons: ['네이티브 모듈 한계', 'iOS 특수 기능'],
    bestFor: ['크로스플랫폼 MVP', '웹+앱 통합'],
    worstFor: ['게임', '고성능 그래픽'],
  },
  {
    id: 'flutter', category: 'mobile',
    label: 'Flutter', emoji: '🦋',
    desc: 'Dart 언어. 픽셀 단위 동일 UI',
    scores: { speed: 8, scale: 9, cost: 9, learning: 7, ecosystem: 8, performance: 9, koreaJobs: 6 },
    setupCmd: 'flutter create my_app',
    monthlyCostUsd: [0, 30],
    learningWeeks: [4, 2],
    pros: ['UI 일관성', '60fps 보장', 'Material·Cupertino'],
    cons: ['Dart 학습', 'Web 부수적'],
    bestFor: ['디자인 일관성', '게임/애니메이션'],
    worstFor: ['JS 환경 통합'],
  },
  {
    id: 'swift', category: 'mobile',
    label: 'Swift / SwiftUI', emoji: '🍎',
    desc: 'iOS 네이티브. 최고 성능',
    scores: { speed: 6, scale: 10, cost: 7, learning: 6, ecosystem: 9, performance: 10, koreaJobs: 8 },
    setupCmd: 'open Xcode',
    monthlyCostUsd: [10, 100],
    learningWeeks: [6, 3],
    pros: ['iOS 최적화', 'Apple API 전부', 'SwiftUI 모던'],
    cons: ['iOS 전용', 'Mac 필수'],
    bestFor: ['iOS 우선', '하드웨어 통합'],
    worstFor: ['크로스플랫폼'],
    koreaNote: '카카오·토스·네이버 모바일 팀 다수 — 시니어 채용',
  },
  {
    id: 'kotlin', category: 'mobile',
    label: 'Kotlin / Jetpack Compose', emoji: '🤖',
    desc: 'Android 네이티브. 최고 성능',
    scores: { speed: 7, scale: 10, cost: 7, learning: 6, ecosystem: 9, performance: 10, koreaJobs: 8 },
    monthlyCostUsd: [10, 100],
    learningWeeks: [5, 3],
    pros: ['Android 최적화', 'Compose UI', 'Google 통합'],
    cons: ['Android 전용'],
    bestFor: ['Android 우선', 'Google 생태'],
    worstFor: ['크로스플랫폼'],
  },
  {
    id: 'tauri', category: 'mobile',
    label: 'Tauri 2 (데스크톱·모바일)', emoji: '🦀',
    desc: 'Rust + 웹뷰. 가벼움 (Electron 대안)',
    scores: { speed: 8, scale: 9, cost: 10, learning: 7, ecosystem: 7, performance: 10, koreaJobs: 3 },
    setupCmd: 'npm create tauri-app@latest',
    monthlyCostUsd: [0, 5],
    learningWeeks: [2, 1],
    pros: ['바이너리 작음 (~3MB)', 'Rust 안전성', '데스크톱+모바일'],
    cons: ['Rust 학습', '웹뷰 차이'],
    bestFor: ['데스크톱 앱', '경량 멀티플랫폼'],
    worstFor: ['모바일 단독'],
  },
]

/* ───── 전체 통합 ───── */
export const ALL_STACKS: Stack[] = [
  ...FRONTENDS, ...BACKENDS, ...DATABASES, ...AUTHS, ...HOSTINGS, ...PAYMENTS, ...ANALYTICS, ...MOBILES,
]

export function findStack(id: string): Stack | undefined {
  return ALL_STACKS.find((s) => s.id === id)
}

export function stacksByCategory(category: Category): Stack[] {
  return ALL_STACKS.filter((s) => s.category === category)
}
