export interface Tool {
  href:  string
  icon:  string
  name:  string
  desc:  string
  badge?: 'hot' | 'new'
}

export interface Category {
  id:    string
  icon:  string
  name:  string
  color: string
  tools: Tool[]
}

export const categories: Category[] = [
  {
    id: 'finance', icon: '💰', name: '금융·재테크', color: '#059669',
    tools: [
      { href: '/tools/finance/salary',   icon: '💴', name: '연봉 실수령액 계산기', desc: '세금·4대보험 떼고 통장에 진짜 꽂히는 그 월급. 2026년 최신 기준 자동 + 인상률·시급 환산.', badge: 'hot' },
      { href: '/tools/finance/loan',     icon: '💳', name: '대출이자 계산기',      desc: '원리금균등·원금균등부터 갈아타기·중도상환·금리 변동까지. 매달 얼마 나갈지 정확하게.' },
      { href: '/tools/finance/dsr',      icon: '🏦', name: 'DSR·LTV·스트레스DSR 계산기', desc: '연소득·집값·금리 한 번 입력으로 DSR·LTV·스트레스DSR 동시 계산. 변동/혼합/고정 금리별 최대 대출 한도까지.', badge: 'new' },
      { href: '/tools/finance/compound', icon: '📈', name: '복리 계산기',          desc: '거치·적립·증액·인플레이션 반영. 시간이 만드는 자산을 시나리오별로 비교.' },
      { href: '/tools/finance/stock',    icon: '📉', name: '주식 물타기 계산기',   desc: '추가 매수 시 평단가가 어디까지 내려갈지 + 회복까지 필요한 상승률을 즉시.' },
      { href: '/tools/finance/vat',      icon: '🧾', name: '부가세 계산기',        desc: '공급가·세액·합계 자유 역산. 견적서·세금계산서 그대로 쓰는 사업자·프리랜서 도구.' },
      { href: '/tools/finance/dividend', icon: '💰', name: '월배당 목표 자산 계산기', desc: '매달 받고 싶은 배당액에서 거꾸로 — 필요한 원금과 월 적립액, ISA·연금 절세까지.', badge: 'hot' },
      { href: '/tools/finance/inheritance', icon: '🏛️', name: '상속·증여세 계산기', desc: '관계별 공제·10년 합산·배우자 공제 반영 정확한 세액 + 분산 증여 시뮬레이션.' },
      { href: '/tools/finance/car-cost', icon: '🚗', name: '자동차 유지비 계산기', desc: '유류·보험·세금·소모품·감가 합한 연간 진짜 비용. 차종·전기차 손익분기 비교.', badge: 'hot' },
      { href: '/tools/finance/car-tax',  icon: '🧾', name: '자동차 세금 종합 계산기', desc: '취득세·자동차세·유류세·공채·환경부담금까지 — 자동차 관련 모든 세금 한 화면에. 친환경차·다자녀·장애인 감면 + 5/10년 누적 시뮬.', badge: 'new' },
      { href: '/tools/finance/historical-money', icon: '💴', name: '한국 화폐가치 환산기', desc: '1960년 50환, 1980년 1만원의 현재 가치는? 圓·환·원 화폐사 + 1945~2026 구매력 환산. 짜장면·집값·월급 시대별 비교.', badge: 'new' },
      { href: '/tools/finance/real-estate', icon: '🏘️', name: '부동산 수익률 계산기', desc: '매매가·임대·대출 레버리지 반영한 자기자본 수익률. 진짜 남는 돈을 확인.' },
      { href: '/tools/finance/housing-score', icon: '🏠', name: '청약 가점 계산기', desc: '84점 만점(무주택 32 + 부양가족 35 + 통장 17) 자동 + 최근 평균 당첨 가점 비교 + 가점 향상 시뮬 + 5가지 특공 자가진단 (2025 기준).', badge: 'new' },
      { href: '/tools/finance/cost-rate', icon: '🍽️', name: '음식점 원가율 계산기', desc: '재료비·배달 수수료·포장재 반영한 실질 원가율과 마진. 메뉴 가격 결정에 바로.' },
      { href: '/tools/finance/installment', icon: '💳', name: '카드 할부 계산기', desc: '할부 개월수별 진짜 이자와 일시불·무이자 비교. 카드 선택의 기준을 숫자로.' },
      { href: '/tools/finance/4-insurance', icon: '🏥', name: '4대보험 계산기', desc: '국민연금·건강·고용·산재 — 근로자/사업주 부담 정확히. 알바·프리랜서 비교까지.' },
      { href: '/tools/finance/ipo-deposit', icon: '💰', name: '공모주 증거금 계산기', desc: '증거금 ↔ 예상 주수 양방향 + 5사6입·청약 한도 자동. 청약일 D-day 메모.', badge: 'new' },
      { href: '/tools/finance/stock-decision', icon: '🧠', name: '주식 매도·매수 심리 진단', desc: '팔까 살까 망설일 때, 행동경제학 7대 편향 자가진단으로 내 결정에 끼어든 감정을 점검. 투자 권유·종목 추천 X.', badge: 'new' },
      { href: '/tools/finance/savings', icon: '💰', name: '저축액 계산기', desc: '수입·지출 → 저축률과 한국 평균 비교 + 6 항아리 분배. 청년도약·ISA 절세 시뮬.', badge: 'new' },
      { href: '/tools/finance/auction', icon: '🏛️', name: '경매 비용 계산기', desc: '낙찰가 + 취득세·명도·체납·수리·대출까지 진짜 들어가는 비용을 시나리오별로.', badge: 'new' },
      { href: '/tools/finance/severance', icon: '💼', name: '퇴직금 실수령액 계산기', desc: '입사·퇴사일과 3개월 급여로 퇴직금·퇴직소득세·실수령 자동. DB/DC/IRP 4모드.', badge: 'new' },
      { href: '/tools/finance/freelance-tax', icon: '💼', name: '프리랜서 종합소득세 계산기', desc: '업종별 단순경비율·8단계 누진세 자동 + 노란우산·연금 절세 시나리오 5종 비교.', badge: 'new' },
      { href: '/tools/finance/rent-jeonse', icon: '🏠', name: '월세·전세 비교 계산기', desc: '전세·월세·반전세 3옵션 동시 비교. 대출이자·기회비용·세액공제 반영한 손익분기.', badge: 'new' },
      { href: '/tools/finance/gold-converter', icon: '🪙', name: '금 단위·가격 계산기', desc: '돈·g·트로이온스·푼·냥 9단위 + 14K/18K/24K 환산. 시세 기반 실거래가까지.', badge: 'new' },
    ],
  },
  {
    id: 'health', icon: '🏃', name: '건강·웰빙', color: '#0891B2',
    tools: [
      { href: '/tools/health/bmi',           icon: '⚖️', name: 'BMI 계산기',                 desc: '키·몸무게로 비만도와 정상 체중 범위. 허리둘레·체지방률 추정까지 한 화면에.' },
      { href: '/tools/health/bmr',           icon: '🔥', name: '기초대사량 계산기',          desc: '기초대사량과 하루 총 소비 칼로리 + 운동일/휴식일별 목표 칼로리 자동.' },
      { href: '/tools/health/weightloss',    icon: '🎯', name: '체중 감량 기간 계산기',     desc: '목표 체중까지 며칠 + 정체기를 반영한 안전 페이스. 식단·운동 칼로리 자동 분리.', badge: 'hot' },
      { href: '/tools/health/pregnancy',     icon: '🤰', name: '임신 주수 계산기',          desc: '지금 임신 몇 주차인지 + 산전 검사·태아 크기·출산 준비를 자동 타임라인으로.' },
      { href: '/tools/health/pet',           icon: '🐾', name: '반려동물 계산기', desc: '강아지·고양이 사람 나이와 사료량·체중 평가·수명 진행률을 한눈에.' },
      { href: '/tools/health/blood-alcohol', icon: '🍺', name: '혈중알코올 계산기',     desc: '지금 운전 가능 시각과 다음날 아침 출근 BAC. 1·2·3차 누적과 ALDH2 분해 속도까지.' },
      { href: '/tools/health/supplement',    icon: '💊', name: '영양제 중복 체크 계산기',   desc: '복용 중인 영양제 50종 자동 합산 → 상한 초과·약물 상호작용 경고.' },
      { href: '/tools/health/uv-protection', icon: '☀️', name: '자외선 지수 계산기', desc: '오늘 UV 지수와 내 피부 타입 기준 일광화상 위험 시간 + SPF 차단제 권장.' },
      { href: '/tools/health/cycle',           icon: '🌙', name: '생리주기·배란일 계산기', desc: '마지막 생리일과 평균 주기로 다음 생리·배란·가임기를 원형 시각화 + phase별 컨디션.', badge: 'hot' },
      { href: '/tools/health/caffeine',        icon: '☕', name: '카페인 잔존량 트래커', desc: '지금 체내 카페인 mg과 취침 시 잔존량을 반감기 5h로 실시간 추적. 24+ 한국 음료 프리셋.', badge: 'new' },
      { href: '/tools/health/sleep-debt',      icon: '😴', name: '수면 부채 트래커', desc: '지난 7·14·30일 누적 수면 부족 시간 + 회복까지 며칠 더 자야 0이 되는지 자동.', badge: 'new' },
    ],
  },
  {
    id: 'cooking', icon: '🍳', name: '요리·식품', color: '#D97706',
    tools: [
      { href: '/tools/cooking/recipe',  icon: '📐', name: '레시피 비율 계산기', desc: '인분만 바꾸면 모든 재료가 비례 자동. 큰술↔g↔ml 환산과 장보기 리스트까지.' },
      { href: '/tools/cooking/thawing', icon: '🧊', name: '해동 시간 계산기',    desc: '냉장·전자레인지·찬물·실온 4가지 해동법 비교 + 식품별 위험도와 시작·완료 시각.' },
      { href: '/tools/cooking/microwave', icon: '🔥', name: '전자레인지 출력 환산기', desc: '600W 레시피를 우리집 800W에선 몇 분? 한국 식품 12종 프리셋 + 카운트다운 타이머.', badge: 'hot' },
      { href: '/tools/cooking/sourdough', icon: '🍞', name: '사워도우 스타터 계산기', desc: '스타터 안정화 진단 + 피크 시간 예측 + 급이 일정 자동 스케줄러.' },
      { href: '/tools/cooking/frying',    icon: '🍳', name: '튀김 시간 계산기',   desc: '재료별 최적 기름 온도와 시간 + 에어프라이어 변환. 바삭함은 디테일에서.' },
      { href: '/tools/cooking/nuts',      icon: '🥜', name: '견과류 섭취량 계산기', desc: '12종 견과류 일일 권장 알 수·칼로리·영양소. 알레르기 필터와 셀레늄 자동 경고.' },
      { href: '/tools/cooking/serving',   icon: '🍽️', name: '1인분 분량 계산기',         desc: 'n인분 식단의 재료별 정확한 분량과 합산 장보기. 채식·비건·글루텐프리 필터.' },
      { href: '/tools/cooking/food-storage', icon: '🧊', name: '식재료 보관 계산기', desc: '냉장·냉동 식재료가 언제까지 안전한지 + 소비 기한 알림으로 음식물 쓰레기 줄이기.' },
      { href: '/tools/cooking/substitute', icon: '🔄', name: '식재료 대체 계산기', desc: '버터가 없을 때, 고추장이 떨어졌을 때 — 50+ 식재료 대체 비율과 비건·GF 옵션.' },
      { href: '/tools/cooking/baker-percent', icon: '🥖', name: '베이커 퍼센트 계산기', desc: '밀가루 100% 기준 모든 재료 비율 자동 + 수분율·르방. 빵 종류별 프리셋 8종.', badge: 'hot' },
      { href: '/tools/cooking/baking-schedule', icon: '🍞', name: '제빵 타임라인 계산기', desc: '완성 시각만 알려주세요. 오토리즈·폴딩·발효·굽기 일정을 시간 단위로 역산.', badge: 'hot' },
      { href: '/tools/cooking/ramen', icon: '🍜', name: '라면 물양 계산기', desc: '라면 개수·국물 농도·토핑별 권장 물양과 시간. 신라면·짜파게티·불닭·비빔면 전부.', badge: 'new' },
      { href: '/tools/cooking/brew', icon: '☕', name: '커피 브루잉 계산기', desc: '핸드드립·콜드브루·에어로프레스 6가지 추출법 + 비율·온도·시간·분쇄도 매트릭스.', badge: 'new' },
      { href: '/tools/cooking/tea', icon: '🍵', name: '차 우리기 계산기', desc: '녹차·말차·우롱·홍차·보이·허브 9종 + 온도/시간/비율 + 냉침 모드와 떫음 게이지.', badge: 'new' },
      { href: '/tools/cooking/baking-recipe', icon: '🧁', name: '제과 레시피 계산기', desc: '마들렌·파운드·쿠키·머핀·마카롱 등 10종 비율 자동 + 식감 보정·틀 용량 환산.', badge: 'new' },
      { href: '/tools/cooking/egg-timer', icon: '🥚', name: '계란 삶는 시간 계산기', desc: '반숙·완숙·잼노른자 8단계 익힘 + 계란 크기·시작 온도 자동 보정 + 실시간 타이머.', badge: 'new' },
      { href: '/tools/cooking/kimjang', icon: '🥬', name: '김장 양 계산기', desc: '가족 수·소비·기간만 알려주면 배추 포기·양념·비용 자동. KAMIS 실시간 시세 연동.', badge: 'new' },
      { href: '/tools/cooking/holiday-table', icon: '🍱', name: '명절 상차림 계산기', desc: '설날·추석·제사 × 차례상·간소·식사 + 인원 입력 → 50종 품목 수량·비용 자동. KAMIS 실시간 시세 + 5열 차례상 배치.', badge: 'new' },
      { href: '/tools/cooking/fruit-syrup', icon: '🍯', name: '과일청 담그기 계산기', desc: '매실청·레몬청·유자청 설탕 비율(1:1) + 필요 유리병 크기·숙성 D-day 일정. 제철 과일 캘린더와 보관 궁합까지.', badge: 'new' },
    ],
  },
  {
    id: 'life', icon: '🎲', name: '생활·재미', color: '#EA580C',
    tools: [
      { href: '/tools/life/lotto',         icon: '🎰', name: '로또 번호 생성기', desc: '8가지 생성 모드 + 번호 분석 + 가상 추첨으로 1등 체감. 당첨금 세후까지.', badge: 'hot' },
      { href: '/tools/life/random',        icon: '🎲', name: '랜덤 추첨기', desc: '룰렛 회전으로 점심·벌칙부터 팀 나누기·자리 배치까지. 모바일에서도 빠른 칩 입력.' },
      { href: '/tools/life/ladder',        icon: '🪜', name: '사다리타기',          desc: '캐릭터 16종 + 6가지 공개 모드 + 카톡 공유. 진짜 한 번에 끝나는 사다리.' },
      { href: '/tools/life/dutch',         icon: '🍻', name: '더치페이 계산기', desc: '한 명이 선결제했을 때 가장 적은 송금 횟수로 정산. 8가지 상황 프리셋 포함.' },
      { href: '/tools/life/zodiac',        icon: '🐯', name: '띠·별자리 계산기',    desc: '내 띠·별자리·60갑자·오행을 한 카드로 + 두 사람 궁합과 가족 띠 비교까지.', badge: 'hot' },
      { href: '/tools/life/travel-tip',    icon: '💵', name: '해외여행 팁 계산기',   desc: '18+ 국가별 식당·택시·호텔·골프·마사지 적정 팁. 만족도 보정과 인원 분할.', badge: 'new' },
      { href: '/tools/life/travel-budget', icon: '✈️', name: '해외여행 예산 계산기', desc: '18+ 도시 × 배낭·중간·럭셔리 3스타일 평균 + 9개 항목 자동 추천을 도넛 차트로.', badge: 'new' },
      { href: '/tools/life/packing',       icon: '🧳', name: '여행 짐 계산기',     desc: '일수·기온·세탁 가능·활동량으로 카테고리별 옷 개수 + 최소·넉넉 2버전.', badge: 'new' },
      { href: '/tools/life/customs',       icon: '📦', name: '관부가세 계산기', desc: '미국·중국·유럽·일본 직구 면세 한도 + 30+ 품목 관세율. 백화점 가격과 직접 비교.', badge: 'new' },
      { href: '/tools/life/pomodoro',      icon: '🍅', name: '뽀모도로 타이머',     desc: '25/5분부터 딥워크·수능까지 7가지 프리셋. 일일·주간 통계와 연속일수 추적.' },
      { href: '/tools/life/alcohol',       icon: '🍺', name: '알코올 도수 계산기',  desc: '소맥·하이볼 황금비율 + 목표 도수 희석과 같은 알코올량 비교.', badge: 'hot' },
      { href: '/tools/life/drake',         icon: '👽', name: '드레이크 방정식 계산기', desc: '외계 문명은 몇 개나 존재할까. 7개 변수를 직접 조정하며 페르미 역설까지.' },
      { href: '/tools/life/laundry-dry',   icon: '🧺', name: '빨래 건조 시간 계산기', desc: '온도·습도·소재별 가장 빠른 건조 조합 + 전기료 비교까지.' },
      { href: '/tools/life/cleaning',      icon: '🧽', name: '상황별 청소 세제 계산기', desc: '화장실·주방·기름때 상황별 추천 세제·희석량 + 락스+산성=염소가스 등 혼합 금지 안전 가이드.', badge: 'new' },
      { href: '/tools/life/monty-hall',    icon: '🚪', name: '몬티홀 시뮬레이터', desc: '바꿔야 유리한 진짜 이유. 3·10·100·1000문 시뮬과 베이즈 추론으로 직관을 깨다.' },
      { href: '/tools/life/fart-risk',     icon: '💨', name: '방귀 위험도 계산기', desc: '가스량·냄새·복부팽만 3축 점수로 원인 진단 + 저FODMAP 대체와 증상별 대처.' },
      { href: '/tools/life/unit-price',    icon: '🏷️', name: '단가 비교 계산기',        desc: '마트·편의점·코스트코 가격을 1ml·1g·1개당 실질 단가로 즉시. 1+1·2+1도 정확히.' },
      { href: '/tools/life/gift-money',    icon: '🧧', name: '축의금·부의금 계산기', desc: '관계·참석 여부로 결혼식 축의금·장례식 부의금 적정액 추천 + 홀수 관례·봉투 문구·신권 매너까지.', badge: 'new' },
    ],
  },
  {
    id: 'sports', icon: '⛳', name: '스포츠', color: '#CA8A04',
    tools: [
      { href: '/tools/sports/fight-weight',    icon: '🥊', name: '격투기 체급 계산기',     desc: '복싱·UFC·MMA 체급별 감량 계획과 D-day 일정 + 위험도 자동 경고.' },
      { href: '/tools/sports/baseball-stats',  icon: '⚾', name: '야구 타율 계산기',   desc: '타율·출루율·장타율·OPS·ERA·WHIP 즉시 계산 + KBO 평균 비교.' },
      { href: '/tools/sports/football-points', icon: '⚽', name: '축구 승점 계산기',  desc: '남은 경기 시나리오로 목표 승점 달성 가능성 + 라이벌 추격 자동 계산.' },
      { href: '/tools/sports/formation',       icon: '⚽', name: '축구 포메이션 생성기', desc: '5·7·9·11인제 22+ 포메이션 + 명단 칩 입력으로 그라운드 위에 시각화. PNG 다운로드.', badge: 'new' },
      { href: '/tools/sports/pace',            icon: '🏃', name: '러닝 페이스 계산기',     desc: '페이스 ↔ 완주 시간 1줄 입력 + 트레드밀 시속과 5km·10km·하프·풀 스플릿.' },
      { href: '/tools/sports/race-predictor',  icon: '🏅', name: '마라톤 기록 계산기', desc: '5km·10km·하프 기록으로 풀코스 예상 시간 + 기온·고도·연령 자동 보정.', badge: 'hot' },
      { href: '/tools/sports/hyrox',           icon: '🏋️', name: '하이록스(HYROX) 계산기', desc: '8km 런 + 8개 스테이션 + 록스존으로 완주 시간 예측 + 목표 페이스 역산 + Open/Pro 부문별 중량표.', badge: 'new' },
      { href: '/tools/sports/hiking-time',     icon: '🥾', name: '등산 시간 계산기',   desc: '한국 100대 명산 35+ 프리셋 + 체력·날씨 보정. 일몰 전 하산 자동 진단.', badge: 'new' },
      { href: '/tools/sports/one-rm',          icon: '🏋️', name: '1RM 계산기',             desc: '5RM·8RM 기록으로 진짜 최대 무게 추정 + RPE 보정과 워밍업 5세트 자동.' },
      { href: '/tools/sports/strength-level',  icon: '💪', name: '스트렝스 레벨 계산기', desc: '3대(스쿼트·벤치·데드) 입력 → 3대 합·윌크스·DOTS 점수 + 체중·성별·연령 보정 레벨(입문~엘리트).', badge: 'new' },
      { href: '/tools/sports/climbing-grade',  icon: '🧗', name: '클라이밍 등급 변환기', desc: '볼더링 V↔Font, 루트 YDS↔French↔UIAA 난이도 환산 + 입문~엘리트 밴드·변환표.', badge: 'new' },
      { href: '/tools/sports/interval-training',icon: '🏃‍♂️', name: '인터벌 훈련 계산기',   desc: 'VDOT 기반 정확한 인터벌 페이스 + 4~16주 풀 트레이닝 스케줄.' },
      { href: '/tools/sports/buildup',         icon: '📈', name: '러닝 빌드업 계산기', desc: '거리·페이스·구간·프로파일 → 구간별 페이스표와 워치 포맷 자동 + 안전성 체크.', badge: 'new' },
      { href: '/tools/sports/lsd',             icon: '🏃', name: 'LSD·이지런 페이스 계산기', desc: '최근 기록으로 이지 페이스 범위·존2 심박 + 회색지대(정크 마일) 경고 + 롱런 보급 플래너.', badge: 'new' },
      { href: '/tools/sports/vo2max',          icon: '🫁', name: 'VO₂ Max 계산기', desc: '쿠퍼·1.5마일·락포트·노르웨이 등 6가지 방법으로 심폐 체력 추정 + 동년배 5단계 등급 + 마라톤 예상 시간 + 강도별 트레이닝 페이스.', badge: 'new' },
      { href: '/tools/sports/golf-handicap',     icon: '⛳', name: '골프 핸디캡 계산기',     desc: 'WHS 핸디캡·코스 핸디캡·스태블포드 + 라운드 자동 저장으로 발전 추이까지.' },
      { href: '/tools/sports/golf-cost',         icon: '🏌️', name: '골프 비용 계산기', desc: '그린피·카트·캐디·식사·교통 1인당 정산 + 회원권 손익 분기점.' },
      { href: '/tools/sports/golf-distance',     icon: '🎯', name: '골프 비거리 계산기', desc: '드라이버·7번 기록으로 전체 클럽 비거리 추정 + 바람·고도·기온 보정.', badge: 'hot' },
      { href: '/tools/sports/grip-size',         icon: '🤝', name: '그립 사이즈 계산기', desc: '손 측정 한 번으로 테니스(L1~L5)·골프(언더/표준/미드/점보)·배드민턴(G2~G6)·스쿼시 4종목 동시 추천.', badge: 'new' },
    ],
  },
  {
    id: 'interior', icon: '🏠', name: '주거·인테리어', color: '#EA580C',
    tools: [
      { href: '/tools/interior/room-area',     icon: '📐', name: '공간 면적 계산기',           desc: '벽·바닥·천장·평수·부피 한 번에 — 도배·페인트·에어컨 평형 계산의 기본.', badge: 'hot' },
      { href: '/tools/interior/ventilation',   icon: '💨', name: '환기량 계산기',     desc: '공간 부피·인원으로 필요 환기량 + 공기청정기 CADR 매칭과 창문 환기 시간.', badge: 'new' },
      { href: '/tools/interior/wallpaper',     icon: '🧱', name: '도배 계산기',         desc: '벽 면적으로 필요한 벽지 롤 수와 셀프 시공 비용 견적.' },
      { href: '/tools/interior/paint',         icon: '🎨', name: '페인트 계산기',       desc: '벽·천장 면적과 칠할 횟수로 필요한 페인트량과 구매 조합.' },
      { href: '/tools/interior/curtain-blind', icon: '🪟', name: '커튼 블라인드 계산기', desc: '창문 사이즈로 커튼·블라인드·롤스크린 추천 사이즈를 자동으로.' },
      { href: '/tools/interior/lighting',      icon: '💡', name: '조명 밝기 계산기',           desc: '공간별 권장 루멘과 조명 개수 + W↔lm 환산과 색온도 가이드.' },
      { href: '/tools/interior/ac-capacity',   icon: '❄️', name: '에어컨 평형 계산기',         desc: '면적·향·층수·단열을 반영한 추천 평형 + BTU·W 환산.', badge: 'hot' },
      { href: '/tools/interior/flooring',      icon: '🪵', name: '바닥재 계산기',       desc: '장판·강화마루·강마루·원목·데코타일 박스 수와 비용 견적.' },
      { href: '/tools/interior/molding',       icon: '📏', name: '몰딩 계산기',           desc: '천장 몰딩·걸레받이·띠몰딩의 길이·개수·비용.' },
      { href: '/tools/interior/roof',          icon: '🏠', name: '지붕 면적 계산기',           desc: '박공·모임·외쪽·평지붕·맞배 5가지 + 물매·처마·로스율 → 자재 면적과 단가.', badge: 'new' },
      { href: '/tools/interior/screw',         icon: '🔩', name: '나사 규격 계산기',     desc: 'M·UNC·UNF·PT·목재·석고 7종 + 탭드릴·관통홀·렌치 사이즈.', badge: 'new' },
      { href: '/tools/interior/bolt-wrench',   icon: '🔧', name: '볼트 스패너 계산기', desc: 'M3~M24 + ISO/DIN/KS vs 옛 JIS 비교 + 알렌렌치·와셔·너트·토크 등급.', badge: 'new' },
      { href: '/tools/interior/pipe',          icon: '🔧', name: '배관 규격 변환기',             desc: 'A호칭·인치·DN 통합 + 강관·PVC·PB·XL·동관·STS 6재질 실제 OD/ID와 유량.', badge: 'new' },
      { href: '/tools/interior/wire',          icon: '⚡', name: '전선 굵기 계산기',     desc: '사용 가전 W에 맞는 전선 굵기와 차단기 + 전압강하 자동. KEC 2021 기준.', badge: 'new' },
      { href: '/tools/interior/rebar',         icon: '🏗️', name: '철근 중량 계산기',             desc: 'KS D 3504 12규격 + 길이별 본수·중량·톤·단가 + 트럭 적재 매칭.', badge: 'new' },
    ],
  },
  {
    id: 'unit', icon: '📐', name: '단위·변환', color: '#7C3AED',
    tools: [
      { href: '/tools/unit/converter',     icon: '📐', name: '단위 변환기',         desc: '길이·무게·온도·압력·당도 등 14가지 분야를 한 번에. 척·치·푼·평·정보·근·돈·홉 같은 한국 전통 도량형도 변환.', badge: 'hot' },
      { href: '/tools/unit/area',          icon: '🏠', name: '평수 변환기',          desc: '아파트 평형·전용·공급·계약면적 환산 + 평형별 방 크기 가이드.' },
      { href: '/tools/unit/size',          icon: '🛍️', name: '사이즈 변환기',    desc: 'US·EU·UK 의류·신발·속옷·반지를 한국 사이즈로 + 브랜드별 차이 가이드.', badge: 'hot' },
      { href: '/tools/unit/battery',       icon: '🔋', name: '배터리 용량 변환기',         desc: 'mAh·Wh·Ah 변환 + 비행기 반입 가능 여부 자동 판정.' },
      { href: '/tools/unit/fuel-economy',  icon: '⛽', name: '연비 변환기',           desc: 'km/L·L/100km·mpg 변환 + 전기차 전비와 연료별 100km 비용 비교.' },
      { href: '/tools/unit/tire-pressure', icon: '🛞', name: '타이어 계산기',       desc: '공기압(psi·kPa·bar) 변환·체크 + 규격 해석·인치업·트레드 마모·DOT 제조주차 교체시기.' },
      { href: '/tools/unit/hardness',      icon: '🛠️', name: '경도(Hardness) 변환기',  desc: 'HRC·HRB·HV·HB·인장강도 동시 환산 (ASTM E140 강철 표). 칼 강재·공구·금속 가공 — 칼덕·메이커·엔지니어용.', badge: 'new' },
      { href: '/tools/unit/viscosity',     icon: '🛢️', name: '점도(Viscosity) 변환기', desc: 'cP·cSt·SUS·Pa·s 동시 환산 + SAE J300 엔진오일(0W-20·5W-30 등)·ISO VG 산업 윤활유 등급 매칭. 자동차 DIY·산업 정비용.', badge: 'new' },
      { href: '/tools/unit/brewing',       icon: '🍺', name: '양조 도수·당도 변환기',   desc: 'Brix·Plato·SG·Baumé·Oechsle 5종 동시 환산 + OG/FG 기반 ABV·Proof + pH/TA 참고. 자가양조·홈와인·잼·치즈 메이커용.', badge: 'new' },
      { href: '/tools/unit/radiation',     icon: '☢️', name: '방사선·전자파 변환기',   desc: 'Sv·rem·Gy·rad·Bq·Ci 동시 환산 + μSv/h ↔ mSv/년 + CT·치과·항공 일상 노출 비교 + SAR·EMF 별도 섹션.', badge: 'new' },
    ],
  },
  {
    id: 'date', icon: '📅', name: '날짜·시간', color: '#DB2777',
    tools: [
      { href: '/tools/date/server-time', icon: '⏱️', name: '실시간 서버 시간', desc: '수강신청·티켓팅을 위한 NTP 동기화 KST를 밀리초로. 카운트다운·알림음 포함.', badge: 'new' },
      { href: '/tools/date/age',         icon: '🎂', name: '나이 계산기', desc: '만 나이·D-day·1만일 기념·생일 카운트다운 + 인생 시간 통계까지 한 화면에.' },
      { href: '/tools/date/dday',        icon: '📅', name: 'D-Day 계산기', desc: '여러 D-day 저장 + 진행률·평일·영업일 페이스 + 반복 D-day.' },
      { href: '/tools/date/military',    icon: '🎖️', name: '군대 전역일 계산기', desc: '입대일 기준 전역일과 복무율을 시각화.' },
      { href: '/tools/date/history-era', icon: '📜', name: '연호·연대 변환기',   desc: '단기·불기·조선왕·간지·일본·중국 연호 동시 변환 + 단군~현재 통합 연표.' },
      { href: '/tools/date/lunar',       icon: '🌙', name: '양력 음력 변환기',         desc: '양력 ↔ 음력 자유 변환 + 60갑자 간지·띠 자동.' },
      { href: '/tools/date/jet-lag',     icon: '✈️', name: '시차 적응 계산기',          desc: '여행 전·중·후 시차 적응 일정과 수면 타이밍 자동 가이드.' },
      { href: '/tools/date/timezone',    icon: '🌐', name: '시간대(타임존) 변환기',     desc: 'UTC·KST·EST·PST·BST·시드니·인도(+5:30)·이란·네팔(+5:45) 동시 변환. DST 자동, 회의 슬롯 추천.', badge: 'new' },
      { href: '/tools/date/schengen',    icon: '🇪🇺', name: '쉥겐 체류일 계산기',         desc: '유럽 무비자 90/180일 규칙 — 출입국 기록으로 남은 체류일·연속 체류·다음 입국 가능일 자동 계산.', badge: 'new' },
      { href: '/tools/date/life-time',   icon: '⏳', name: '생애 시간 계산기',         desc: '기대수명 기준 살아온 시간·앞으로의 시간을 행동 가치로 환산해 보여줍니다.', badge: 'hot' },
    ],
  },
  {
    id: 'art', icon: '🎨', name: '예술·창작', color: '#9333EA',
    tools: [
      /* 🎵 음악 */
      { href: '/tools/art/vocal-range', icon: '🎤', name: '음역대 측정기', desc: '마이크로 실시간 음정 감지로 내 최저·최고음 측정 + 한국 노래 30+곡 키 매칭.', badge: 'new' },
      { href: '/tools/art/bpm',       icon: '🎛️', name: 'BPM 딜레이 계산기', desc: 'BPM만 입력하면 딜레이·리버브 ms 값 자동. 음악 프로듀서·홈레코딩 필수.' },
      { href: '/tools/art/frequency', icon: '🎵', name: '주파수↔음정 변환기',    desc: 'Hz ↔ 음정 변환 + MIDI 번호와 파장 계산. 튜닝과 사운드 디자인용.' },
      { href: '/tools/art/capo',      icon: '🎸', name: '기타 카포 계산기', desc: '원곡 키와 카포 위치로 변환된 코드 + 쉬운 코드 추천.' },
      { href: '/tools/art/tap-tempo', icon: '👆', name: '탭 템포 계산기',         desc: '박자에 맞춰 탭하면 BPM 자동 측정 + 메트로놈.', badge: 'hot' },
      { href: '/tools/art/chord',     icon: '🎹', name: '코드 구성음 계산기',     desc: 'Cmaj7·Dm7 등 코드의 구성음과 역방향 검색 + 다이아토닉 코드표.' },
      { href: '/tools/art/scale',     icon: '🎼', name: '스케일 음계 계산기',     desc: '12키 × 12스케일 + 피아노·기타 지판 시각화 + 7 모드 비교와 MIDI 재생.', badge: 'new' },
      /* 🎨 디자인·미술 */
      { href: '/tools/art/color',     icon: '🎨', name: '색상 코드 변환기', desc: 'HEX·RGB·HSL·OKLCH 변환 + WCAG 대비비 + 팔레트·Tailwind 매칭·이미지 색 추출.', badge: 'hot' },
      { href: '/tools/art/gradient-generator', icon: '🌈', name: 'CSS 그라디언트 생성기', desc: 'Linear·Radial·Conic·Mesh 5종 × OKLCH·LAB 보간 + Tailwind/SwiftUI/Flutter 코드.', badge: 'new' },
      { href: '/tools/art/golden-ratio',  icon: '🌀', name: '황금 비율 계산기',    desc: 'φ = 1.618 가로·세로 + 황금 직사각형·나선 시각화 + 16:9·A4·인스타·유튜브 비교.' },
      { href: '/tools/art/paint-mix', icon: '🎨', name: '색상 혼합 계산기', desc: '물감·빛·RYB 색 혼합 시뮬 + ml/g 분량 환산 + ΔE 색 매칭과 자주 쓰는 레시피.', badge: 'new' },
      { href: '/tools/art/knit-gauge', icon: '🧶', name: '뜨개질 게이지 계산기', desc: '10cm² 게이지로 패턴 코·단수 변환 + 한국 사이즈별 코 계산·늘림 균등 분배.', badge: 'new' },
      { href: '/tools/art/exposure',  icon: '📸', name: '사진 노출 계산기',    desc: '조리개·셔터·ISO 3축을 자유롭게 + 옵션 잠금으로 등가 노출 시뮬. ND·Sunny 16 포함.', badge: 'new' },
      { href: '/tools/art/fov',       icon: '📷', name: '카메라 화각 계산기', desc: '풀프레임~스마트폰 7종 센서 × 4-800mm 35mm 환산 + 화각·시야 너비·등가 조리개.', badge: 'new' },
      { href: '/tools/art/print-resolution', icon: '🖨️', name: '인쇄 해상도 계산기', desc: '인쇄 크기·용도(DPI)로 필요한 최소 픽셀·메가픽셀 + 내 이미지로 인쇄 품질 역산과 품질별 최대 크기.', badge: 'new' },
      /* ✍️ 글쓰기·콘텐츠 */
      { href: '/tools/art/charcount', icon: '🔡', name: '글자수 세기',          desc: '공백 포함·제외 실시간 카운트. SNS·자소서·논문 글자 수 체크.', badge: 'hot' },
      { href: '/tools/art/lorem',     icon: '📝', name: '더미 텍스트 생성기', desc: '문단·버튼·카드·리뷰·JSON 더미를 UI 목업에 바로 붙여 쓸 수 있게.' },
      { href: '/tools/art/morse-code', icon: '📡', name: '모스 부호·NATO 변환기', desc: '한글·영문 모스 부호 양방향 변환 + 소리·빛 재생·SOS + NATO 음성기호(Alfa·Bravo) 철자 변환.', badge: 'new' },
    ],
  },
  {
    id: 'edu', icon: '🔬', name: '교육·학습', color: '#0D9488',
    tools: [
      { href: '/tools/edu/planet-comparison', icon: '🪐', name: '행성 비교 계산기', desc: '8개 행성에서 내 몸무게·나이·하루 길이가 어떻게 달라지는지 시각화.', badge: 'hot' },
      { href: '/tools/edu/cosmic-calendar',   icon: '🌌', name: '코스믹 캘린더',     desc: '138억 년 우주 역사를 1년 달력으로 압축한 인터랙티브 타임라인.' },
      { href: '/tools/edu/circuit-simulator', icon: '⚡', name: '옴의 법칙 계산기', desc: '직렬·병렬 회로 전압·전류·저항·전력 시각화 + 단계별 풀이와 빈출 7문제.' },
      { href: '/tools/edu/sound-speed',        icon: '🔊', name: '음속 계산기',     desc: '천둥·번개 거리·소리 도달 시간·반향·RT60. 빛 vs 소리를 직관적으로.' },
      { href: '/tools/edu/room-mode',          icon: '🔊', name: '룸 모드 계산기',       desc: '방 가로·세로·높이로 축방향·접선·사선 모드 + 슈로더 주파수와 베이스 트랩 가이드.', badge: 'new' },
      { href: '/tools/edu/review-interval',    icon: '🧠', name: '복습 간격 계산기',     desc: '에빙하우스 망각곡선·SM-2 알고리즘으로 다음 복습일 자동 + 학습 항목 관리.', badge: 'hot' },
      { href: '/tools/edu/cognitive-test',     icon: '🧠', name: '인지 능력 테스트',     desc: '반응속도·스트룹·이중 과제로 집중력과 인지 처리 속도를 게임처럼 측정.' },
      { href: '/tools/edu/fermi-estimate',     icon: '🧮', name: '페르미 추정 계산기',   desc: '막막한 문제를 변수로 쪼개고 시나리오로 비교해 대략 답을 추정하는 사고력 훈련.' },
      { href: '/tools/edu/gpa-converter',       icon: '🎓', name: '학점(GPA) 환산기',     desc: '한국 4.5·4.3 ↔ 미국 4.0 ↔ 영국 학위 등급. WES·비례·평어 3방식 동시 비교 + 한국 대학별 만점 가이드.', badge: 'new' },
      { href: '/tools/edu/sci-units',           icon: '🔬', name: '과학 단위 변환기',     desc: 'SI 접두어·과학적/공학적 표기 상호 변환 + 옹스트롬·광년·eV 등 과학 스케일 단위 환산 + 주요 물리 상수표.', badge: 'new' },
      { href: '/tools/edu/sig-figs',            icon: '📏', name: '유효숫자·오차 계산기', desc: '측정값 유효숫자 자동 판별·반올림 + 절대·상대·백분율오차 + 두 측정값의 오차 전파(±·×·÷·거듭제곱). 실험 보고서용.', badge: 'new' },
    ],
  },
  {
    id: 'dev', icon: '🖥️', name: '개발자', color: '#0EA5E9',
    tools: [
      { href: '/tools/dev/base64',    icon: '🔐', name: 'Base64 인코더/디코더', desc: '텍스트 ↔ Base64 즉시 변환 + URL 안전 모드.' },
      { href: '/tools/dev/tech-stack', icon: '🛠️', name: '기술 스택 추천기', desc: '프로젝트 시나리오로 Frontend·Backend·DB·Auth·Hosting·Payment 풀스택 자동 추천.', badge: 'new' },
      { href: '/tools/dev/json',      icon: '📋', name: 'JSON 포맷터',          desc: 'JSON 정렬·압축·검증·트리 뷰 + TypeScript 인터페이스 자동 + YAML/CSV 변환.' },
      { href: '/tools/dev/css-converter', icon: '🎨', name: 'CSS 단위 변환기',    desc: 'px·rem·em 변환 + clamp()·aspect-ratio 자동 생성.' },
      { href: '/tools/dev/number-base',   icon: '🔢', name: '진법 변환기',       desc: '2·8·10·16진 변환 + 비트 시각화 + 2의 보수·ASCII·비트 연산.' },
      { href: '/tools/dev/hash', icon: '🔒', name: '해시 생성기', desc: 'MD5·SHA-1·SHA-256·SHA-512 동시 + HMAC 서명·파일 무결성·SRI 해시. 전부 브라우저 처리.', badge: 'new' },
      { href: '/tools/dev/regex', icon: '🔍', name: '정규식 테스트기', desc: 'JavaScript 정규식 실시간 매칭·하이라이트 + 캡처·치환·분할 + 한국 데이터 패턴 30+.', badge: 'new' },
      { href: '/tools/dev/yaml-json', icon: '📄', name: 'YAML ↔ JSON 변환기', desc: '양방향 변환·유효성 + Kubernetes·Docker Compose·GitHub Actions 12개 예시.', badge: 'new' },
      { href: '/tools/dev/url-encode', icon: '🔗', name: 'URL 인코더/디코더', desc: 'URL 인코드/디코드 + URL 분해와 쿼리 파라미터 표 편집. UTM·추적 파라미터 일괄 정리.', badge: 'new' },
      { href: '/tools/dev/curl', icon: '🌀', name: 'cURL 변환기', desc: 'cURL 명령어를 fetch·axios·Python·Node·Go 5 언어로 즉시 변환. 한국 API 12개 예시.', badge: 'new' },
      { href: '/tools/dev/http-status', icon: '🌐', name: 'HTTP 상태 코드 검색기', desc: 'HTTP 65+ 상태 코드 한국어 설명·발생 시기·해결 힌트. CORS·JWT·Lambda 시나리오.', badge: 'new' },
      { href: '/tools/dev/network-test', icon: '🌐', name: '인터넷 회선 진단', desc: '핑·지터·실패율·다운로드 + 인터파크·예스24·멜론·KBO 응답으로 티켓팅 적합도 판정.', badge: 'new' },
      { href: '/tools/dev/token-counter', icon: '🪙', name: 'AI 토큰 카운터', desc: 'GPT·Claude·Gemini 토큰 수와 컨텍스트 사용량 동시 추정 + 입력·출력 단가 반영 API 비용. 한국어 비효율 인사이트.', badge: 'new' },
      { href: '/tools/dev/og-preview', icon: '🖼️', name: 'OG 미리보기 시뮬레이터', desc: '카카오톡·페이스북·X·LinkedIn·Slack에서 공유될 때의 카드를 한 화면에. 메타태그 검증 + 코드 생성 + 카카오톡 캐시 가이드.', badge: 'new' },
    ],
  },
]

// 전체 툴 flat 배열 (검색·홈 인기 툴용)
export const allTools: Tool[] = categories.flatMap(c => c.tools)

// 총 툴 수
export const totalTools = allTools.length
